name: Deploy pipeline
on:
  push:
    branches:
        - main
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Application
        run: echo "Building the application..."
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: echo "Running tests..."
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        run: echo "Deploying the application..."
